apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplejava
  namespace: default
spec:
  minReadySeconds: 3
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 60
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: simplejava
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9797"
      labels:
        app: simplejava
        pipeline-date: "2024031642693"
    spec:
      imagePullSecrets:
        - name: ghcr-login-secret
      containers:
      - name: simplejava
        image: ghcr.io/ds886/simplejava:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 9898
          protocol: TCP
        - name: http-metrics
          containerPort: 9797
          protocol: TCP
        - name: grpc
          containerPort: 9999
          protocol: TCP
        env:
        - name: PODINFO_UI_COLOR
          value: "#34577c"
        livenessProbe:  null
        readinessProbe: null
        resources: {}
