# https://github.com/bmoussaud/cnb-springboot/blob/master/k8s/02-deployment.yml

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: simplejava
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simplejava
  template:
    metadata:
      labels:
        app: simplejava
    spec:
      containers:
        - image: ghcr.io/ds886/simplejava
          name: app
          livenessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/liveness
            initialDelaySeconds: 60
            periodSeconds: 2
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/readiness
            initialDelaySeconds: 10
